// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXrXpxeVG2tUBhgp-1bTr3dOVsHRD7Awk',
    appId: '1:1071738785343:web:a214cba5e60ec6dd87f28a',
    messagingSenderId: '1071738785343',
    projectId: 'small-cargo-t',
    authDomain: 'small-cargo-t.firebaseapp.com',
    storageBucket: 'small-cargo-t.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXrXpxeVG2tUBhgp-1bTr3dOVsHRD7Awk',
    appId: '1:1071738785343:android:a214cba5e60ec6dd87f28a',
    messagingSenderId: '1071738785343',
    projectId: 'small-cargo-t',
    storageBucket: 'small-cargo-t.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXrXpxeVG2tUBhgp-1bTr3dOVsHRD7Awk',
    appId: '1:1071738785343:ios:a214cba5e60ec6dd87f28a',
    messagingSenderId: '1071738785343',
    projectId: 'small-cargo-t',
    storageBucket: 'small-cargo-t.firebasestorage.app',
    iosClientId: '1071738785343-xxxxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.smallcargo.smallCargo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXrXpxeVG2tUBhgp-1bTr3dOVsHRD7Awk',
    appId: '1:1071738785343:ios:a214cba5e60ec6dd87f28a',
    messagingSenderId: '1071738785343',
    projectId: 'small-cargo-t',
    storageBucket: 'small-cargo-t.firebasestorage.app',
    iosClientId: '1071738785343-xxxxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.smallcargo.smallCargo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXrXpxeVG2tUBhgp-1bTr3dOVsHRD7Awk',
    appId: '1:1071738785343:web:a214cba5e60ec6dd87f28a',
    messagingSenderId: '1071738785343',
    projectId: 'small-cargo-t',
    authDomain: 'small-cargo-t.firebaseapp.com',
    storageBucket: 'small-cargo-t.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
